export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const EDIT_RESTAURANT = 'EDIT_RESTAURANT';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const INITIALIZE_RESTAURANTS = 'INITIALIZE_RESTAURANTS';

